begin transaction;
drop view if exists v_channel;
drop view if exists v_message;
drop table if exists messages;
drop table if exists channel_members;
drop table if exists channels_invitations;
drop table if exists channels;
drop table if exists users_invitations;
drop table if exists users;
commit;
