package model

import model.channels.ChannelName
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith

class ChannelNameTest {
    @Test
    fun `successful channel name instantiation test`() {
        ChannelName(name = "channelName", ownerName = "ownerName")
    }

    @Test
    fun `exception generated by an invalid channel name test`() {
        assertFailsWith<IllegalArgumentException> { ChannelName(name = "", ownerName = "ownerName") }
    }

    @Test
    fun `exception generated by an invalid owner name test`() {
        assertFailsWith<IllegalArgumentException> { ChannelName(name = "channelName", ownerName = "") }
    }

    @Test
    fun `unique channel name test`() {
        val ownerName = "ownerName"
        val chanelName = "channelName"
        val channelName1 = ChannelName(name = chanelName, ownerName = ownerName)
        assertEquals("@$ownerName/$chanelName", channelName1.fullName)
    }
}