package model

import model.channels.ChannelInfo
import model.channels.ChannelName
import kotlin.test.Test
import kotlin.test.assertFailsWith

class ChannelInfoTest {
	@Test
	fun `successful channel info instantiation test`() {
		ChannelInfo(1u, ChannelName(name = "channelName", ownerName = "ownerName"))
	}

	@Test
	fun `exception generated by an invalid channel name test`() {
		assertFailsWith<IllegalArgumentException> { ChannelInfo(1u, ChannelName(name = "", ownerName = "")) }
	}
}
