package model

import model.channels.ChannelInfo
import model.channels.ChannelName
import model.messages.Message
import model.users.UserInfo
import java.time.LocalDateTime
import kotlin.test.Test
import kotlin.test.assertFailsWith

class MessageTest {
	private val msgId: UInt = 1u
	private val msg: String = "Hello World"
	private val user: UserInfo = UserInfo(1u, "user1")
	private val channel: ChannelInfo = ChannelInfo(1u, ChannelName("channel1", "user2"))
	private val creationTime: LocalDateTime = LocalDateTime.now()

	@Test
	fun `successful message instantiation test`() {
		Message(msgId, msg, user, channel, creationTime)
	}

	@Test
	fun `exception generated by an empty message test`() {
		assertFailsWith<IllegalArgumentException> {
			Message(msgId, "", user, channel, creationTime)
		}
	}
}
