package model

import org.eclipse.jetty.util.security.Password
import kotlin.test.Test
import kotlin.test.assertFailsWith

class UserTest {
    private val uId: UInt = 1u
    private val passwordTest = Password("password")
    private val usernameTest = "username"
    private val blankUsername = ""
    @Test
    fun `successful user instantiation test`() {
        User(uId, usernameTest, passwordTest)
    }

    @Test
    fun `exception generated by an invalid username test`() {
        assertFailsWith<IllegalArgumentException> { User(uId, blankUsername, passwordTest) }
    }
}